# Generated by Django 3.0.7 on 2020-07-05 09:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_colour', models.CharField(max_length=30)),
                ('colour', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=40)),
                ('descriptions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('links', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pages.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('descriptions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('links', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pages.Image')),
                ('tools', models.ManyToManyField(to='pages.Tool')),
            ],
        ),
    ]
