# Generated by Django 3.0.7 on 2020-07-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200705_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(default='static/images/default.jpg', upload_to='images/'),
        ),
    ]
