# Generated by Django 3.0.7 on 2020-07-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200706_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(default='media/images/work_blog/default.jpg', upload_to='media/images/work_blog'),
        ),
    ]
