# Generated by Django 3.0.7 on 2020-07-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200706_0226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
