# Generated by Django 3.0.7 on 2020-07-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200707_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour',
            name='shade',
            field=models.CharField(default='Blue', max_length=30),
            preserve_default=False,
        ),
    ]
